"""Fine-tune the plate detector (Python side of M7) with Ultralytics, and export an NMS-free ONNX.

Why Ultralytics here: the v8 loss, the task-aligned assigner and mosaic already exist there, and the
pretrained yolov8n weights are the whole point of starting from transfer learning. The C++ side has
its own trainer for the recognizer (`jlpr train`), and the detector trainer is a port of
yolov8_cpp's (tracked as M7b in RESUME) — it is not a stub in Python and a stub in C++, it is a
different amount of work in each and the RESUME says so.

  python tools/train_det.py --data data/det --real data/det_real --epochs 60 --imgsz 640
  python tools/train_det.py ... --export models/plate_det_v8n.onnx

The export is deliberately **without NMS**: pure/infer_v8.hpp does the threshold+NMS in 40 lines, and
the ops an in-graph NMS needs (NonMaxSuppression/GatherND/ScatterND/NonZero) are far outside what the
C++/WASM interpreter implements. A plain export writes boxes as **cxcywh** in input pixels, which is
why `BoxFmt`/`--fmt` exists on both sides.
"""
import argparse
import os
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")


def write_data_yaml(path, roots, val_root, imgsz):
    """Ultralytics wants one yaml; several generated dirs can be listed as a train set."""
    train = [os.path.abspath(os.path.join(r, "images")) for r in roots]
    val = os.path.abspath(os.path.join(val_root, "images"))
    with open(path, "w", encoding="utf-8") as f:
        f.write("# generated by tools/train_det.py — class 0 is the plate, nothing else\n")
        f.write("train:\n")
        for t in train:
            f.write("  - %s\n" % t.replace("\\", "/"))
        f.write("val: %s\n" % val.replace("\\", "/"))
        f.write("nc: 1\nnames: [plate]\n")
    print("wrote %s (train: %d dirs, val: %s)" % (path, len(train), val))
    return path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", action="append", default=[], help="generated det dir (repeatable)")
    ap.add_argument("--val", default="", help="dir used for validation (defaults to the last --data)")
    ap.add_argument("--weights", default="yolov8n.pt")
    ap.add_argument("--epochs", type=int, default=60)
    ap.add_argument("--imgsz", type=int, default=640)
    ap.add_argument("--batch", type=int, default=16)
    ap.add_argument("--lr", type=float, default=0.002)
    ap.add_argument("--project", default="runs/det")
    ap.add_argument("--name", default="plate")
    ap.add_argument("--export", default="")
    ap.add_argument("--export-imgsz", dest="export_imgsz", type=int, action="append", default=[])
    ap.add_argument("--yaml", default="scratch/plate_det.yaml")
    ap.add_argument("--export-only", dest="export_only", default="",
                    help="skip training and export this .pt (recover from a failed export without "
                         "paying for the epochs again)")
    a = ap.parse_args()
    if not a.data and not a.export_only:
        raise SystemExit("pass at least one --data <dir with images/ and labels/>")

    try:
        from ultralytics import YOLO
    except ImportError:
        print("ultralytics is not installed here.\n"
              "  pip install ultralytics    (or run colab/train_det.ipynb, which does it for you)")
        return 2

    os.makedirs(os.path.dirname(a.yaml) or ".", exist_ok=True)
    yaml_path = write_data_yaml(a.yaml, a.data, a.val or a.data[-1], a.imgsz) if a.data else ""

    if a.export_only:
        best = a.export_only
    else:
        model = YOLO(a.weights)
        model.train(data=yaml_path, epochs=a.epochs, imgsz=a.imgsz, batch=a.batch, lr0=a.lr,
                    project=a.project, name=a.name, exist_ok=True,
                    # plates are small and thin: keep mosaic, drop vertical flips, wide scale jitter
                    mosaic=1.0, fliplr=0.5, flipud=0.0, degrees=5.0, scale=0.6, translate=0.15,
                    hsv_h=0.015, hsv_s=0.6, hsv_v=0.4, close_mosaic=10)
        # Ask the trainer where it actually put the weights. Composing project/name/weights/best.pt is
        # wrong whenever Ultralytics' settings prepend a runs_dir (it wrote runs/detect/runs/det/plate,
        # and a 71-minute training run then died at the export step for want of this line).
        best = str(getattr(model.trainer, "best", "") or
                   os.path.join(a.project, a.name, "weights", "best.pt"))
    print("best weights: %s" % best)

    if a.export:
        sizes = a.export_imgsz or [a.imgsz]
        for sz in sizes:
            m = YOLO(best)
            # simplify=True is NOT cosmetic: a plain export leaves Shape/Gather/Concat plumbing in the
            # head, and pure/onnx_run.hpp implements neither ("tensor '/model.22/Gather_output_0' is
            # missing"). onnxslim constant-folds it away into a graph our interpreter can run.
            path = m.export(format="onnx", imgsz=sz, opset=13, simplify=True, nms=False, dynamic=False)
            dst = a.export if len(sizes) == 1 else a.export.replace(".onnx", "_%d.onnx" % sz)
            os.makedirs(os.path.dirname(dst) or ".", exist_ok=True)
            shutil.copyfile(path, dst)
            print("exported %s (imgsz=%d, no NMS -> boxes are cxcywh, use --fmt cxcywh)" % (dst, sz))
    return 0


if __name__ == "__main__":
    sys.exit(main())
